force-app/extension/main/default/objects/Property_Details__c/Property_Details__c.object-meta.xml
<CustomObject>
    <label>Property Details</label>
    <nameField>
        <label>Property Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/extension/main/default/objects/Property_Details__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Property Details</relationshipLabel>
    <relationshipName>Property_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/extension/main/default/classes/PropertyDetailsControllerTest.cls
@isTest
public class PropertyDetailsControllerTest {
    @isTest
    public static void PropertyDetailsControllerTest() {
        Property__c pack = new Property__c(Name = 'Test Property');
        insert pack;
        Property_Details__c propertyDetail = new Property_Details__c(Name = 'Test Property Detail');
        insert propertyDetail;
        Test.startTest();
        String barredName = PropertyDetailsController.getBarredDetailName(propertyDetail.Id);
        Test.stopTest();
        System.assertEquals(propertyDetail.Name + 'Bar', barredName, 'that name was not correctly barred');
    }
}